### ISSUE TITLE
self-host init database failed

### ISSUE THREAD

**Issue by ninehills** [llmonitor/llmonitor#26] opened 2023-09-26 03:00 UTC
Use Supabase SQL Editor to run `setup-dump.sql`, then failed with follow message:

```
Error running SQL: Invalid SQL query
```

file: https://raw.githubusercontent.com/llmonitor/llmonitor/main/selfhosting/setup-dump.sql

<img width="367" alt="image" src="https://github.com/llmonitor/llmonitor/assets/270298/dfb88a19-28af-42b7-b56e-9c7aa21d06ab">

**Comment by ninehills** [comment] 2023-09-26 03:25
fix :
```patch
diff --git a/selfhosting/setup-dump.sql b/selfhosting/setup-dump.sql
index 19aa364..04034c5 100644
--- a/selfhosting/setup-dump.sql
+++ b/selfhosting/setup-dump.sql
@@ -90,6 +90,12 @@ ALTER TABLE public.profile ENABLE ROW LEVEL SECURITY;
 ALTER TABLE public.run ENABLE ROW LEVEL SECURITY;
 
 
+--
+-- Name: idx_run_parent_run; Type: INDEX; Schema: public; Owner: -
+--
+
+CREATE INDEX idx_run_parent_run ON public.run USING btree (parent_run);
+
 --
 -- Name: profile Profiles are viewable by users who created them.; Type: POLICY; Schema: public; Owner: -
 --
@@ -136,16 +142,6 @@ CREATE POLICY run_owner_policy ON public.run USING ((( SELECT app.owner
   WHERE (app.id = run.app)) = auth.uid()));
 
 
-
---
--- Name: run run_owner_policy; Type: POLICY; Schema: public; Owner: -
---
-
-CREATE POLICY app_user_owner_policy ON public.app_user USING ((( SELECT app.owner
-   FROM public.app
-  WHERE (app.id = app_user.app)) = auth.uid()));
-
-
 --
 -- Name: get_related_runs(uuid); Type: FUNCTION; Schema: public; Owner: -
 --
@@ -254,9 +250,3 @@ END; $function$
     
 
 
---
--- Name: idx_run_parent_run; Type: INDEX; Schema: public; Owner: -
---
-
-CREATE INDEX idx_run_parent_run ON public.run USING btree (parent_run);
-
```

**Comment by pAkalpa** [comment] 2023-09-26 04:11
The commit e36e498 solved the issue. Please Update Repo and try again.

**Comment by ninehills** [comment] 2023-09-26 04:42
> @ninehills The commit [e36e498](https://github.com/llmonitor/llmonitor/commit/e36e4980e25fda9fccd61a7c00e4d034404b414e) solved the issue. Please Update Repo and try again.

I have already used the latest version, but it still gives that error.

**Comment by pAkalpa** [comment] 2023-09-26 05:58
@ninehills I apologize for suggesting that it was fixed in the first place. My mistake!. The error appears to be occurring at line number 144 in the setup-dump.sql file. This might be because the public.app_user table hasn't been created yet. You can check the specific code snippet [ here ](https://github.com/llmonitor/llmonitor/blob/0c72a656090a6a00463da5c66447741fcb2cb178/selfhosting/setup-dump.sql#L144C1-L146C49)
@vincelwt @hughcrt any comments
![Screenshot 2023-09-26 111641](https://github.com/llmonitor/llmonitor/assets/43250159/a44c5445-790b-4690-94dd-9e09981e0149)

**Comment by Igosuki** [comment] 2023-09-27 09:04
This worked for me :
```

CREATE TABLE "public"."app_user" (
    "created_at" timestamptz DEFAULT now(),
    "app" uuid,
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "external_id" text,
    "last_seen" timestamptz,
    "props" jsonb,
    PRIMARY KEY ("id")
);

CREATE POLICY app_user_owner_policy ON public.app_user USING ((( SELECT app.owner
   FROM public.app
  WHERE (app.id = app_user.app)) = auth.uid()));

```

**Comment by andrey59412678** [comment] 2023-09-28 05:31
@Igosuki that works for me, just had to add quotes around user

however, there is still something missing: column "profile.team_owner". I had to remove from the query in the code to make it work

**Comment by prazevj** [comment] 2023-10-04 07:09
@hughcrt Thank you. While using the self-hosted version in the callback handler code 
`res = requests.get(f"{self.__api_url}/api/app/{self.__app_id}")`

this URL is giving me Internal Server Error. I tried changing the `DEFAULT_API_URL` and also have tried setting the `LLMONITOR_API_URL`, `LLMONITOR_APP_ID`. Unable to connect to the api endpoint. Any workaround or troubleshooting steps could you recommend ?

**Comment by nkuehn** [comment] 2023-10-05 12:04
I can confirm the above issues (initial SQL not working, requires fixes discussed above) plus the following
- email verification has localhost:3000 as redirect URL  (vs. the vercel project URL - no documentation on where / how to tell the system its deployment URL).  After manually changing the URL in the email, the redirect from there with  `?code=....` has localhost:3000  in it again.   -> needs to be set at https://supabase.com/dashboard/project/{your-project-id}/auth/url-configuration  
-  406 authentication failures from the frontend when calling supabase REST APIs.  (even after deleting the user  and all data in supabase and re-trying) - "JSON object requested, multiple (or no) rows returned"
- frontend making various calls to `llmonitor.featurebase.app` which is does not really look like a self-deployed setup

I can help testing a new version but can't really help with development

**Comment by vincelwt** [comment] 2023-10-05 15:20
Hi guys! Apologies about those issues, we're currently fully focused on fixing some core issues with the python module and feedback tracking and will work on improving self hosting as soon as we have a bit more time on our hand.

@nkuehn 
- Email verification endpoint is configured in Supabase I think? If you're self hosting supabase that would be in the Supaabse env variables 
- Not sure about the 406 errors, could you share screenshot of the console logs so we can try to pinpoint where they are?
- Good call about `llmonitor.featurebase.app`, I'll disable those in the self hosted version

**Comment by nkuehn** [comment] 2023-10-09 11:09
> If you're self hosting supabase that would be in the Supaabse env variables

I can't see a  related env var [in the template](https://github.com/llmonitor/llmonitor/blob/main/.env.example)  - there's only the ones for resend.com  

> Not sure about the 406 errors, could you share screenshot of the console logs so we can try to pinpoint where they are?

This is the first one, all following fail the same way:

`https://{my-tenant}.supabase.co/rest/v1/profile?select=id%2Cemail%2Cname%2Cupdated_at%2Cplan%2Cteam_owner&id=eq.6cfa5cd5-1413-4293-a1f5-1163e0423e26`

Result is a 406, the body contains:
```json
{
    "code": "PGRST116",
    "details": "The result contains 0 rows",
    "hint": null,
    "message": "JSON object requested, multiple (or no) rows returned"
}
```

My best guess is that the initialization with the first user is not working as intended.  After resetting everything and retrying, in supabase there is an account under "authentication" but all the tables are still empty.  So the initial setup click flow is not actually creating a user in llmonitor, just the supabase auth entry.     My first guess is that is silently fails somewhere e.g. because the DB schema is not correct.  my vercel logs are empty.    For me:  pausing this until there is a reliable DB schema setup script that does not make the app fail.

**Comment by hughcrt** [comment] 2023-10-28 16:51
Hi, 
We've fixed self hosting. It's been tested internally and by one of our users and it seems to work fine. Here are the instructions:

1. Setup a new [Supabase](https://supabase.com/) project (don't reuse the previous one, as the setup script will fail if the tables already exist).
2. Clone [the repo](https://github.com/llmonitor/llmonitor/) and deploy it to Vercel
3. Look at `.env.example` to see what environment variables you need to set on Vercel
4. Open the Supabase Admin dashboard
   4.1. Go to `Database > Webhooks` and click on "Enable webhooks"
   4.2. Copy the content of `setup-dump.sql` in the SQL editor. Replace `<your_vercel_project_url>` by the actual URL at the end of the script and run it.
   4.3. Go to `Authentication > Url Configuration` and replace `http://localhost:3000` by your Vercel project url.
   
Please let me know if it works for you!
@ninehills @Igosuki @nkuehn @prazevj

**Closed by hughcrt** 2023-10-28 16:51 UTC
